### PR TITLE
Switch to PostgreSQL

### PR DESCRIPTION
**Pull request by turnerm**
Changes needed to use Postgres instead of sqlite. I confirmed that there are no more errors when building the DB and views.

### CODE REVIEW

**Review by davidmegginson — CHANGES_REQUESTED** [review]
Thanks for doing this, Monica.

The change to SERIAL looks good. I'm curious about the change from DATETIME to TIMESTAMP -- it's probably fine, but I think PostgreSQL supports DATETIME; if I'm not mistaken, what's the benefit of TIMESTAMP (just curious).

I did request changes only because there's a conflict that needs to be merged.

**Comment by davidmegginson** [comment]
Note that I did not test with PostgreSQL because I haven't set up an environment yet, but I'm assuming Monica's already done that.

**Comment by turnerm** [comment]
Thanks so much for the review @davidmegginson. I've fixed the conflicts, and I can confirm that I've tested with Postgres. When I use `datetime` I get: 

`ERROR:  type "datetime" does not exist`

The [postgres docs](https://www.postgresql.org/docs/9.5/datatype-datetime.html) seem to confirm that `timestamp` should be used.

**Review by davidmegginson — APPROVED** [review]
Sounds good, then. If PostgreSQL doesn't support DATETIME, then TIMESTAMP will work fine.

**Comment by davidmegginson** [comment]
Here's a sweet little target you could optionally add to the bottom of the Makefile, to launch an interactive psql session inside the container:

```Makefile
explore:
	@docker exec -it ${PG_CONTAINER_NAME} psql -U ${PG_USER} -d ${PG_DATABASE}
```

**Comment by turnerm** [comment]
@davidmegginson great suggestion, thanks!

**Pull request merged**
