### PR TITLE
Auto incrememt

### PR DESCRIPTION
**Pull request by turnerm**
When working with the DB file in the pipeline repository, I found the auto-increment was not properly working unless I changed it to sqlite specific syntax. 

Unrelated question: this branch is actually branched from `mime-type-to-format`, @davidmegginson do you know if there is any way I can base my PR off of that branch but still somehow create it in the OCHA DAP repo? Just so that the unique changes are clear even more merging the mime-type branch.

### CODE REVIEW

**Comment by mcarans** [comment]
This could be a problem as we'd need to use serial for PostgreSQL and autoincrement for SQLite.

**Comment by davidmegginson** [comment]
> Unrelated question: this branch is actually branched from `mime-type-to-format`, @davidmegginson do you know if there is any way I can base my PR off of that branch but still somehow create it in the OCHA DAP repo? Just so that the unique changes are clear even more merging the mime-type branch.

The main branch is using _format_ now, so you can base your fork on that and should be OK going forward.

**Comment by davidmegginson** [comment]
FWIW, SQLite is _supposed_ to autoincrement an integer primary key when not provided explicitly, though the current code doesn't test that:

https://www.sqlite.org/autoinc.html

"AUTOINCREMENT" is not standard ANSI SQL, though MySQL also uses it. PostgreSQL is obsessive about standards compliance, so it uses the ANSI SQL "SERIAL" data type for an integer that's supposed to be incremented automatically, but SQLite doesn't support that. I thought it best to leave it blank for now, then switch to SERIAL when we stop prototyping and shift to PostgreSQL, but we do need to figure out why SQLite isn't auto incrementing by default.

**Comment by turnerm** [comment]
@davidmegginson really good point, I think the issue was actually using SERIAL instead of INTEGER and as you pointed out, AUTOINCREMENT is not needed. I've updated the PR, let me know what you think.

**Pull request merged**
